---

version: '3.8'
services:
  db:
    build: ./mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: myapp
      MYSQL_USER: myappuser
      MYSQL_PASSWORD: myapppass
    volumes:
    - db-data:/var/lib/mysql
  php:
    build: ./php
    depends_on:
    - db
    ports:
    - 8562:8000
    volumes:
    - ./work:/work
  phpmyadmin:
   image: phpmyadmin/phpmyadmin:latest
   ports:
     - 8888:80
   depends_on:
     - db

volumes:
  db-data: